global:
  registry: docker.io/tpaktopucm
  tag: "1.0"
  pullPolicy: IfNotPresent
  namespace: weather

vault:
  enabled: true
  addr: "https://vault.vault.svc.cluster.local:8200"
  role: "weather-app"
  authPath: "auth/kubernetes"
  secretPath: "secret/data/weather-app"
  skipVerify: true
  initContainer:
    image: "hashicorp/vault-k8s:1.3.1"
    pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: weather-app-sa
  annotations: {}

service1:
  name: weather-service1
  image: weather-service1
  tag: "1.1"
  port: 8080
  targetPort: 8080
  
  rollout:
    enabled: true
    replicas: 3
    strategy:
      canary:
        steps:
        - setWeight: 20
        - pause: { duration: "2m" }
        - analysis:
            templates:
            - templateName: success-rate
            args:
            - name: service-name
              value: weather-service1
        - setWeight: 50
        - pause: { duration: "5m" }
        - setWeight: 80
        - pause: { duration: "2m" }
        - setWeight: 100
        
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
      
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

service2:
  name: weather-service2
  image: weather-service2
  tag: "1.0"
  replicaCount: 1
  port: 8081
  targetPort: 8081
  
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi

service:
  type: ClusterIP

ingress:
  enabled: true
  className: "nginx"
  host: "weather-forecast.local"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s

analysis:
  successRate:
    enabled: true
    interval: "2m"
    count: 3
    failureLimit: 1
    failureCondition: "result < 95"
    prometheus:
      address: "http://prometheus.monitoring:9090"
