global:
  registry: docker.io/tpaktopucm
  tag: "1.0"
  pullPolicy: IfNotPresent

service1:
  name: weather-service1
  image: weather-service1
  replicaCount: 2
  port: 8080
  targetPort: 8080
  
  canary:
    enabled: false
    replicaCount: 1
    weight: 10
    
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
      
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70
    customMetrics:
      - type: Pods
        pods:
          metric:
            name: requests_per_second
          target:
            type: AverageValue
            averageValue: "10"

service2:
  name: weather-service2
  image: weather-service2
  replicaCount: 2
  port: 8081
  targetPort: 8081
  
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi

service:
  type: ClusterIP
  
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: weather-forecast.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
