{{- if .Values.analysis.successRate.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "weather-forecast.labels" . | nindent 4 }}
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: {{ .Values.analysis.successRate.interval }}
    count: {{ .Values.analysis.successRate.count }}
    failureLimit: {{ .Values.analysis.successRate.failureLimit }}
    provider:
      prometheus:
        address: {{ .Values.analysis.successRate.prometheus.address }}
        query: |
          100 * (
            sum(rate(http_requests_total{
              status=~"2..|3..",
              service="{{`{{args.service-name}}`}}"
            }[5m])) 
            / 
            sum(rate(http_requests_total{
              service="{{`{{args.service-name}}`}}"
            }[5m]))
          )
    successCondition: {{ .Values.analysis.successRate.successCondition }}
    failureCondition: {{ .Values.analysis.successRate.failureCondition }}
{{- end }}
