{{- if and .Values.ingress.enabled .Values.ingress.gateway.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.ingress.gateway.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "weather-forecast.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.ingress.host }}
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: weather-tls-secret
    hosts:
    - {{ .Values.ingress.host }}
{{- end }}
