{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-forecast-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "weather-forecast.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /weather
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service1.name }}-stable
            port:
              number: {{ .Values.service1.port }}
      - path: /condition
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service2.name }}
            port:
              number: {{ .Values.service2.port }}
{{- end }}
