{{- if .Values.service1.canary.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service1.name }}-canary
  labels:
    app: {{ .Values.service1.name }}
    version: canary
spec:
  replicas: {{ .Values.service1.canary.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.service1.name }}
      version: canary
  template:
    metadata:
      labels:
        app: {{ .Values.service1.name }}
        version: canary
    spec:
      containers:
      - name: {{ .Values.service1.name }}
        image: "{{ .Values.global.registry }}/{{ .Values.service1.image }}:{{ .Values.global.tag }}-canary"
        imagePullPolicy: {{ .Values.global.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service1.targetPort }}
        env:
        - name: SERVICE2_URL
          value: "http://{{ .Values.service2.name }}:{{ .Values.service2.port }}/condition"
        resources:
          {{- toYaml .Values.service1.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service1.targetPort }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service1.targetPort }}
          initialDelaySeconds: 5
          periodSeconds: 5
{{- end }}
