apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service2.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "weather-forecast.labels" . | nindent 4 }}
    app: {{ .Values.service2.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service2.port }}
      targetPort: {{ .Values.service2.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.service2.name }}
