{{- if .Values.vault.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.service1.name }}-vault-secret
  namespace: {{ .Values.global.namespace }}
  annotations:
    vault.security.banzaicloud.io/vault-addr: {{ .Values.vault.addr | quote }}
    vault.security.banzaicloud.io/vault-role: {{ .Values.vault.role | quote }}
    vault.security.banzaicloud.io/vault-skip-verify: {{ .Values.vault.skipVerify | quote }}
    vault.security.banzaicloud.io/vault-path: "secret/data/weather-app"
  labels:
    {{- include "weather-forecast.labels" . | nindent 4 }}
type: Opaque
stringData:
  SERVICE2_URL: vault:secret/data/weather-app#service2_url
  LOG_LEVEL: vault:secret/data/weather-app#log_level
{{- end }}
