{{- if .Values.ingress.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.service1.name }}-vs
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "weather-forecast.labels" . | nindent 4 }}
spec:
  hosts:
  - {{ .Values.ingress.host }}
  gateways:
  - {{ .Values.ingress.gateway.name }}
  http:
  - name: primary
    match:
    - uri:
        prefix: /weather
    route:
    - destination:
        host: {{ .Values.service1.name }}
        port:
          number: {{ .Values.service1.port }}
      weight: 100
    fault:
      delay:
        percentage:
          value: 0.1
        fixedDelay: 5s
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.service1.name }}-dr
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "weather-forecast.labels" . | nindent 4 }}
spec:
  host: {{ .Values.service1.name }}
  subsets:
  - name: stable
    labels:
      version: stable
  - name: canary
    labels:
      version: canary
{{- end }}
